lane :test do
  accessibility_test(
    project_id: "*******",
    gcloud_service_key_file: "fastlane/client-secret.json",
    devices:
      [
        {
          model: "shamu",
          version: "22",
          locale: "ja_JP",
          orientation: "portrait"
        }
      ],
    app_apk: "fastlane/app.apk",
    timeout: "10m",
    firebase_test_lab_results_bucket: "*******",
    download_dir: ".accessibility",
    github_owner: "*******",
    github_repository: "*******",
    github_pr_number: "*******",
    github_api_token: "*******"
  )
end
