// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/google/android/apps/common/testing/accessibility/framework/uielement/AndroidFramework.proto

package com.google.android.apps.common.testing.accessibility.framework.uielement.proto;

public final class AndroidFrameworkProtos {
    private AndroidFrameworkProtos() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }
    public interface RectProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.RectProto)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional int32 left = 1;</code>
         */
        boolean hasLeft();
        /**
         * <code>optional int32 left = 1;</code>
         */
        int getLeft();

        /**
         * <code>optional int32 top = 2;</code>
         */
        boolean hasTop();
        /**
         * <code>optional int32 top = 2;</code>
         */
        int getTop();

        /**
         * <code>optional int32 right = 3;</code>
         */
        boolean hasRight();
        /**
         * <code>optional int32 right = 3;</code>
         */
        int getRight();

        /**
         * <code>optional int32 bottom = 4;</code>
         */
        boolean hasBottom();
        /**
         * <code>optional int32 bottom = 4;</code>
         */
        int getBottom();
    }
    /**
     * <pre>
     * Proto representation of Rect
     * Next index: 5
     * </pre>
     *
     * Protobuf type {@code com.google.android.apps.common.testing.accessibility.framework.uielement.proto.RectProto}
     */
    public  static final class RectProto extends
            com.google.protobuf.GeneratedMessageLite<
                    RectProto, RectProto.Builder> implements
            // @@protoc_insertion_point(message_implements:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.RectProto)
            RectProtoOrBuilder {
        private RectProto() {
        }
        private int bitField0_;
        public static final int LEFT_FIELD_NUMBER = 1;
        private int left_;
        /**
         * <code>optional int32 left = 1;</code>
         */
        public boolean hasLeft() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 left = 1;</code>
         */
        public int getLeft() {
            return left_;
        }
        /**
         * <code>optional int32 left = 1;</code>
         */
        private void setLeft(int value) {
            bitField0_ |= 0x00000001;
            left_ = value;
        }
        /**
         * <code>optional int32 left = 1;</code>
         */
        private void clearLeft() {
            bitField0_ = (bitField0_ & ~0x00000001);
            left_ = 0;
        }

        public static final int TOP_FIELD_NUMBER = 2;
        private int top_;
        /**
         * <code>optional int32 top = 2;</code>
         */
        public boolean hasTop() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 top = 2;</code>
         */
        public int getTop() {
            return top_;
        }
        /**
         * <code>optional int32 top = 2;</code>
         */
        private void setTop(int value) {
            bitField0_ |= 0x00000002;
            top_ = value;
        }
        /**
         * <code>optional int32 top = 2;</code>
         */
        private void clearTop() {
            bitField0_ = (bitField0_ & ~0x00000002);
            top_ = 0;
        }

        public static final int RIGHT_FIELD_NUMBER = 3;
        private int right_;
        /**
         * <code>optional int32 right = 3;</code>
         */
        public boolean hasRight() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 right = 3;</code>
         */
        public int getRight() {
            return right_;
        }
        /**
         * <code>optional int32 right = 3;</code>
         */
        private void setRight(int value) {
            bitField0_ |= 0x00000004;
            right_ = value;
        }
        /**
         * <code>optional int32 right = 3;</code>
         */
        private void clearRight() {
            bitField0_ = (bitField0_ & ~0x00000004);
            right_ = 0;
        }

        public static final int BOTTOM_FIELD_NUMBER = 4;
        private int bottom_;
        /**
         * <code>optional int32 bottom = 4;</code>
         */
        public boolean hasBottom() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int32 bottom = 4;</code>
         */
        public int getBottom() {
            return bottom_;
        }
        /**
         * <code>optional int32 bottom = 4;</code>
         */
        private void setBottom(int value) {
            bitField0_ |= 0x00000008;
            bottom_ = value;
        }
        /**
         * <code>optional int32 bottom = 4;</code>
         */
        private void clearBottom() {
            bitField0_ = (bitField0_ & ~0x00000008);
            bottom_ = 0;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, left_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, top_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt32(3, right_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt32(4, bottom_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, left_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, top_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, right_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, bottom_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        /**
         * <pre>
         * Proto representation of Rect
         * Next index: 5
         * </pre>
         *
         * Protobuf type {@code com.google.android.apps.common.testing.accessibility.framework.uielement.proto.RectProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto, Builder> implements
                // @@protoc_insertion_point(builder_implements:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.RectProto)
                com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProtoOrBuilder {
            // Construct using com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>optional int32 left = 1;</code>
             */
            public boolean hasLeft() {
                return instance.hasLeft();
            }
            /**
             * <code>optional int32 left = 1;</code>
             */
            public int getLeft() {
                return instance.getLeft();
            }
            /**
             * <code>optional int32 left = 1;</code>
             */
            public Builder setLeft(int value) {
                copyOnWrite();
                instance.setLeft(value);
                return this;
            }
            /**
             * <code>optional int32 left = 1;</code>
             */
            public Builder clearLeft() {
                copyOnWrite();
                instance.clearLeft();
                return this;
            }

            /**
             * <code>optional int32 top = 2;</code>
             */
            public boolean hasTop() {
                return instance.hasTop();
            }
            /**
             * <code>optional int32 top = 2;</code>
             */
            public int getTop() {
                return instance.getTop();
            }
            /**
             * <code>optional int32 top = 2;</code>
             */
            public Builder setTop(int value) {
                copyOnWrite();
                instance.setTop(value);
                return this;
            }
            /**
             * <code>optional int32 top = 2;</code>
             */
            public Builder clearTop() {
                copyOnWrite();
                instance.clearTop();
                return this;
            }

            /**
             * <code>optional int32 right = 3;</code>
             */
            public boolean hasRight() {
                return instance.hasRight();
            }
            /**
             * <code>optional int32 right = 3;</code>
             */
            public int getRight() {
                return instance.getRight();
            }
            /**
             * <code>optional int32 right = 3;</code>
             */
            public Builder setRight(int value) {
                copyOnWrite();
                instance.setRight(value);
                return this;
            }
            /**
             * <code>optional int32 right = 3;</code>
             */
            public Builder clearRight() {
                copyOnWrite();
                instance.clearRight();
                return this;
            }

            /**
             * <code>optional int32 bottom = 4;</code>
             */
            public boolean hasBottom() {
                return instance.hasBottom();
            }
            /**
             * <code>optional int32 bottom = 4;</code>
             */
            public int getBottom() {
                return instance.getBottom();
            }
            /**
             * <code>optional int32 bottom = 4;</code>
             */
            public Builder setBottom(int value) {
                copyOnWrite();
                instance.setBottom(value);
                return this;
            }
            /**
             * <code>optional int32 bottom = 4;</code>
             */
            public Builder clearBottom() {
                copyOnWrite();
                instance.clearBottom();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.RectProto)
        }
        protected final Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                Object arg0, Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto other = (com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto) arg1;
                    left_ = visitor.visitInt(
                            hasLeft(), left_,
                            other.hasLeft(), other.left_);
                    top_ = visitor.visitInt(
                            hasTop(), top_,
                            other.hasTop(), other.top_);
                    right_ = visitor.visitInt(
                            hasRight(), right_,
                            other.hasRight(), other.right_);
                    bottom_ = visitor.visitInt(
                            hasBottom(), bottom_,
                            other.hasBottom(), other.bottom_);
                    if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                            .INSTANCE) {
                        bitField0_ |= other.bitField0_;
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                            (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                            (com.google.protobuf.ExtensionRegistryLite) arg1;
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                default: {
                                    if (!parseUnknownField(tag, input)) {
                                        done = true;
                                    }
                                    break;
                                }
                                case 8: {
                                    bitField0_ |= 0x00000001;
                                    left_ = input.readInt32();
                                    break;
                                }
                                case 16: {
                                    bitField0_ |= 0x00000002;
                                    top_ = input.readInt32();
                                    break;
                                }
                                case 24: {
                                    bitField0_ |= 0x00000004;
                                    right_ = input.readInt32();
                                    break;
                                }
                                case 32: {
                                    bitField0_ |= 0x00000008;
                                    bottom_ = input.readInt32();
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                                new com.google.protobuf.InvalidProtocolBufferException(
                                        e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {    synchronized (com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto.class) {
                        if (PARSER == null) {
                            PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                        }
                    }
                    }
                    return PARSER;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.RectProto)
        private static final com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new RectProto();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.RectProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<RectProto> PARSER;

        public static com.google.protobuf.Parser<RectProto> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }

    public interface CharSequenceProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.CharSequenceProto)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional string text = 1;</code>
         */
        boolean hasText();
        /**
         * <code>optional string text = 1;</code>
         */
        java.lang.String getText();
        /**
         * <code>optional string text = 1;</code>
         */
        com.google.protobuf.ByteString
        getTextBytes();

        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        java.util.List<com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto>
        getSpanList();
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto getSpan(int index);
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        int getSpanCount();
    }
    /**
     * <pre>
     * Proto representation of a CharSequence
     * Next index: 3
     * </pre>
     *
     * Protobuf type {@code com.google.android.apps.common.testing.accessibility.framework.uielement.proto.CharSequenceProto}
     */
    public  static final class CharSequenceProto extends
            com.google.protobuf.GeneratedMessageLite<
                    CharSequenceProto, CharSequenceProto.Builder> implements
            // @@protoc_insertion_point(message_implements:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.CharSequenceProto)
            CharSequenceProtoOrBuilder {
        private CharSequenceProto() {
            text_ = "";
            span_ = emptyProtobufList();
        }
        private int bitField0_;
        public static final int TEXT_FIELD_NUMBER = 1;
        private java.lang.String text_;
        /**
         * <code>optional string text = 1;</code>
         */
        public boolean hasText() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string text = 1;</code>
         */
        public java.lang.String getText() {
            return text_;
        }
        /**
         * <code>optional string text = 1;</code>
         */
        public com.google.protobuf.ByteString
        getTextBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(text_);
        }
        /**
         * <code>optional string text = 1;</code>
         */
        private void setText(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            text_ = value;
        }
        /**
         * <code>optional string text = 1;</code>
         */
        private void clearText() {
            bitField0_ = (bitField0_ & ~0x00000001);
            text_ = getDefaultInstance().getText();
        }
        /**
         * <code>optional string text = 1;</code>
         */
        private void setTextBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            text_ = value.toStringUtf8();
        }

        public static final int SPAN_FIELD_NUMBER = 2;
        private com.google.protobuf.Internal.ProtobufList<com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto> span_;
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        public java.util.List<com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto> getSpanList() {
            return span_;
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        public java.util.List<? extends com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProtoOrBuilder>
        getSpanOrBuilderList() {
            return span_;
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        public int getSpanCount() {
            return span_.size();
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        public com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto getSpan(int index) {
            return span_.get(index);
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        public com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProtoOrBuilder getSpanOrBuilder(
                int index) {
            return span_.get(index);
        }
        private void ensureSpanIsMutable() {
            if (!span_.isModifiable()) {
                span_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(span_);
            }
        }

        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        private void setSpan(
                int index, com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureSpanIsMutable();
            span_.set(index, value);
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        private void setSpan(
                int index, com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.Builder builderForValue) {
            ensureSpanIsMutable();
            span_.set(index, builderForValue.build());
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        private void addSpan(com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureSpanIsMutable();
            span_.add(value);
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        private void addSpan(
                int index, com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureSpanIsMutable();
            span_.add(index, value);
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        private void addSpan(
                com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.Builder builderForValue) {
            ensureSpanIsMutable();
            span_.add(builderForValue.build());
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        private void addSpan(
                int index, com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.Builder builderForValue) {
            ensureSpanIsMutable();
            span_.add(index, builderForValue.build());
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        private void addAllSpan(
                java.lang.Iterable<? extends com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto> values) {
            ensureSpanIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, span_);
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        private void clearSpan() {
            span_ = emptyProtobufList();
        }
        /**
         * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
         */
        private void removeSpan(int index) {
            ensureSpanIsMutable();
            span_.remove(index);
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeString(1, getText());
            }
            for (int i = 0; i < span_.size(); i++) {
                output.writeMessage(2, span_.get(i));
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(1, getText());
            }
            for (int i = 0; i < span_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, span_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        /**
         * <pre>
         * Proto representation of a CharSequence
         * Next index: 3
         * </pre>
         *
         * Protobuf type {@code com.google.android.apps.common.testing.accessibility.framework.uielement.proto.CharSequenceProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto, Builder> implements
                // @@protoc_insertion_point(builder_implements:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.CharSequenceProto)
                com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProtoOrBuilder {
            // Construct using com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>optional string text = 1;</code>
             */
            public boolean hasText() {
                return instance.hasText();
            }
            /**
             * <code>optional string text = 1;</code>
             */
            public java.lang.String getText() {
                return instance.getText();
            }
            /**
             * <code>optional string text = 1;</code>
             */
            public com.google.protobuf.ByteString
            getTextBytes() {
                return instance.getTextBytes();
            }
            /**
             * <code>optional string text = 1;</code>
             */
            public Builder setText(
                    java.lang.String value) {
                copyOnWrite();
                instance.setText(value);
                return this;
            }
            /**
             * <code>optional string text = 1;</code>
             */
            public Builder clearText() {
                copyOnWrite();
                instance.clearText();
                return this;
            }
            /**
             * <code>optional string text = 1;</code>
             */
            public Builder setTextBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setTextBytes(value);
                return this;
            }

            /**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public java.util.List<com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto> getSpanList() {
                return java.util.Collections.unmodifiableList(
                        instance.getSpanList());
            }
            /**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public int getSpanCount() {
                return instance.getSpanCount();
            }/**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto getSpan(int index) {
                return instance.getSpan(index);
            }
            /**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public Builder setSpan(
                    int index, com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto value) {
                copyOnWrite();
                instance.setSpan(index, value);
                return this;
            }
            /**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public Builder setSpan(
                    int index, com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.Builder builderForValue) {
                copyOnWrite();
                instance.setSpan(index, builderForValue);
                return this;
            }
            /**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public Builder addSpan(com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto value) {
                copyOnWrite();
                instance.addSpan(value);
                return this;
            }
            /**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public Builder addSpan(
                    int index, com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto value) {
                copyOnWrite();
                instance.addSpan(index, value);
                return this;
            }
            /**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public Builder addSpan(
                    com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.Builder builderForValue) {
                copyOnWrite();
                instance.addSpan(builderForValue);
                return this;
            }
            /**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public Builder addSpan(
                    int index, com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.Builder builderForValue) {
                copyOnWrite();
                instance.addSpan(index, builderForValue);
                return this;
            }
            /**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public Builder addAllSpan(
                    java.lang.Iterable<? extends com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto> values) {
                copyOnWrite();
                instance.addAllSpan(values);
                return this;
            }
            /**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public Builder clearSpan() {
                copyOnWrite();
                instance.clearSpan();
                return this;
            }
            /**
             * <code>repeated .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto span = 2;</code>
             */
            public Builder removeSpan(int index) {
                copyOnWrite();
                instance.removeSpan(index);
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.CharSequenceProto)
        }
        protected final Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                Object arg0, Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    span_.makeImmutable();
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto other = (com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto) arg1;
                    text_ = visitor.visitString(
                            hasText(), text_,
                            other.hasText(), other.text_);
                    span_= visitor.visitList(span_, other.span_);
                    if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                            .INSTANCE) {
                        bitField0_ |= other.bitField0_;
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                            (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                            (com.google.protobuf.ExtensionRegistryLite) arg1;
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                default: {
                                    if (!parseUnknownField(tag, input)) {
                                        done = true;
                                    }
                                    break;
                                }
                                case 10: {
                                    String s = input.readString();
                                    bitField0_ |= 0x00000001;
                                    text_ = s;
                                    break;
                                }
                                case 18: {
                                    if (!span_.isModifiable()) {
                                        span_ =
                                                com.google.protobuf.GeneratedMessageLite.mutableCopy(span_);
                                    }
                                    span_.add(
                                            input.readMessage(com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.parser(), extensionRegistry));
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                                new com.google.protobuf.InvalidProtocolBufferException(
                                        e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {    synchronized (com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto.class) {
                        if (PARSER == null) {
                            PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                        }
                    }
                    }
                    return PARSER;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.CharSequenceProto)
        private static final com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new CharSequenceProto();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.CharSequenceProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<CharSequenceProto> PARSER;

        public static com.google.protobuf.Parser<CharSequenceProto> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }

    public interface SpanProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional int32 start = 1;</code>
         */
        boolean hasStart();
        /**
         * <code>optional int32 start = 1;</code>
         */
        int getStart();

        /**
         * <code>optional int32 end = 2;</code>
         */
        boolean hasEnd();
        /**
         * <code>optional int32 end = 2;</code>
         */
        int getEnd();

        /**
         * <code>optional int32 flags = 3;</code>
         */
        boolean hasFlags();
        /**
         * <code>optional int32 flags = 3;</code>
         */
        int getFlags();

        /**
         * <code>optional .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType type = 4;</code>
         */
        boolean hasType();
        /**
         * <code>optional .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType type = 4;</code>
         */
        com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.SpanType getType();

        /**
         * <code>optional string url = 5;</code>
         */
        boolean hasUrl();
        /**
         * <code>optional string url = 5;</code>
         */
        java.lang.String getUrl();
        /**
         * <code>optional string url = 5;</code>
         */
        com.google.protobuf.ByteString
        getUrlBytes();

        /**
         * <code>optional string span_class_name = 6;</code>
         */
        boolean hasSpanClassName();
        /**
         * <code>optional string span_class_name = 6;</code>
         */
        java.lang.String getSpanClassName();
        /**
         * <code>optional string span_class_name = 6;</code>
         */
        com.google.protobuf.ByteString
        getSpanClassNameBytes();
    }
    /**
     * <pre>
     * Proto representation of a Spanned
     * Next index: 7
     * </pre>
     *
     * Protobuf type {@code com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto}
     */
    public  static final class SpanProto extends
            com.google.protobuf.GeneratedMessageLite<
                    SpanProto, SpanProto.Builder> implements
            // @@protoc_insertion_point(message_implements:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto)
            SpanProtoOrBuilder {
        private SpanProto() {
            url_ = "";
            spanClassName_ = "";
        }
        /**
         * <pre>
         * Span types used by the test framework
         * Next index: 3
         * </pre>
         *
         * Protobuf enum {@code com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType}
         */
        public enum SpanType
                implements com.google.protobuf.Internal.EnumLite {
            /**
             * <code>UNKNOWN = 0;</code>
             */
            UNKNOWN(0),
            /**
             * <code>CLICKABLE = 1;</code>
             */
            CLICKABLE(1),
            /**
             * <code>URL = 2;</code>
             */
            URL(2),
            ;

            /**
             * <code>UNKNOWN = 0;</code>
             */
            public static final int UNKNOWN_VALUE = 0;
            /**
             * <code>CLICKABLE = 1;</code>
             */
            public static final int CLICKABLE_VALUE = 1;
            /**
             * <code>URL = 2;</code>
             */
            public static final int URL_VALUE = 2;


            public final int getNumber() {
                return value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static SpanType valueOf(int value) {
                return forNumber(value);
            }

            public static SpanType forNumber(int value) {
                switch (value) {
                    case 0: return UNKNOWN;
                    case 1: return CLICKABLE;
                    case 2: return URL;
                    default: return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<SpanType>
            internalGetValueMap() {
                return internalValueMap;
            }
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    SpanType> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<SpanType>() {
                        public SpanType findValueByNumber(int number) {
                            return SpanType.forNumber(number);
                        }
                    };

            private final int value;

            private SpanType(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType)
        }

        private int bitField0_;
        public static final int START_FIELD_NUMBER = 1;
        private int start_;
        /**
         * <code>optional int32 start = 1;</code>
         */
        public boolean hasStart() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 start = 1;</code>
         */
        public int getStart() {
            return start_;
        }
        /**
         * <code>optional int32 start = 1;</code>
         */
        private void setStart(int value) {
            bitField0_ |= 0x00000001;
            start_ = value;
        }
        /**
         * <code>optional int32 start = 1;</code>
         */
        private void clearStart() {
            bitField0_ = (bitField0_ & ~0x00000001);
            start_ = 0;
        }

        public static final int END_FIELD_NUMBER = 2;
        private int end_;
        /**
         * <code>optional int32 end = 2;</code>
         */
        public boolean hasEnd() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 end = 2;</code>
         */
        public int getEnd() {
            return end_;
        }
        /**
         * <code>optional int32 end = 2;</code>
         */
        private void setEnd(int value) {
            bitField0_ |= 0x00000002;
            end_ = value;
        }
        /**
         * <code>optional int32 end = 2;</code>
         */
        private void clearEnd() {
            bitField0_ = (bitField0_ & ~0x00000002);
            end_ = 0;
        }

        public static final int FLAGS_FIELD_NUMBER = 3;
        private int flags_;
        /**
         * <code>optional int32 flags = 3;</code>
         */
        public boolean hasFlags() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 flags = 3;</code>
         */
        public int getFlags() {
            return flags_;
        }
        /**
         * <code>optional int32 flags = 3;</code>
         */
        private void setFlags(int value) {
            bitField0_ |= 0x00000004;
            flags_ = value;
        }
        /**
         * <code>optional int32 flags = 3;</code>
         */
        private void clearFlags() {
            bitField0_ = (bitField0_ & ~0x00000004);
            flags_ = 0;
        }

        public static final int TYPE_FIELD_NUMBER = 4;
        private int type_;
        /**
         * <code>optional .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType type = 4;</code>
         */
        public boolean hasType() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType type = 4;</code>
         */
        public com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.SpanType getType() {
            com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.SpanType result = com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.SpanType.forNumber(type_);
            return result == null ? com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.SpanType.UNKNOWN : result;
        }
        /**
         * <code>optional .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType type = 4;</code>
         */
        private void setType(com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.SpanType value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000008;
            type_ = value.getNumber();
        }
        /**
         * <code>optional .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType type = 4;</code>
         */
        private void clearType() {
            bitField0_ = (bitField0_ & ~0x00000008);
            type_ = 0;
        }

        public static final int URL_FIELD_NUMBER = 5;
        private java.lang.String url_;
        /**
         * <code>optional string url = 5;</code>
         */
        public boolean hasUrl() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional string url = 5;</code>
         */
        public java.lang.String getUrl() {
            return url_;
        }
        /**
         * <code>optional string url = 5;</code>
         */
        public com.google.protobuf.ByteString
        getUrlBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(url_);
        }
        /**
         * <code>optional string url = 5;</code>
         */
        private void setUrl(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000010;
            url_ = value;
        }
        /**
         * <code>optional string url = 5;</code>
         */
        private void clearUrl() {
            bitField0_ = (bitField0_ & ~0x00000010);
            url_ = getDefaultInstance().getUrl();
        }
        /**
         * <code>optional string url = 5;</code>
         */
        private void setUrlBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000010;
            url_ = value.toStringUtf8();
        }

        public static final int SPAN_CLASS_NAME_FIELD_NUMBER = 6;
        private java.lang.String spanClassName_;
        /**
         * <code>optional string span_class_name = 6;</code>
         */
        public boolean hasSpanClassName() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional string span_class_name = 6;</code>
         */
        public java.lang.String getSpanClassName() {
            return spanClassName_;
        }
        /**
         * <code>optional string span_class_name = 6;</code>
         */
        public com.google.protobuf.ByteString
        getSpanClassNameBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(spanClassName_);
        }
        /**
         * <code>optional string span_class_name = 6;</code>
         */
        private void setSpanClassName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000020;
            spanClassName_ = value;
        }
        /**
         * <code>optional string span_class_name = 6;</code>
         */
        private void clearSpanClassName() {
            bitField0_ = (bitField0_ & ~0x00000020);
            spanClassName_ = getDefaultInstance().getSpanClassName();
        }
        /**
         * <code>optional string span_class_name = 6;</code>
         */
        private void setSpanClassNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000020;
            spanClassName_ = value.toStringUtf8();
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, start_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, end_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt32(3, flags_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeEnum(4, type_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeString(5, getUrl());
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeString(6, getSpanClassName());
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, start_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, end_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, flags_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(4, type_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(5, getUrl());
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(6, getSpanClassName());
            }
            size += unknownFields.getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        /**
         * <pre>
         * Proto representation of a Spanned
         * Next index: 7
         * </pre>
         *
         * Protobuf type {@code com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto, Builder> implements
                // @@protoc_insertion_point(builder_implements:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto)
                com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProtoOrBuilder {
            // Construct using com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>optional int32 start = 1;</code>
             */
            public boolean hasStart() {
                return instance.hasStart();
            }
            /**
             * <code>optional int32 start = 1;</code>
             */
            public int getStart() {
                return instance.getStart();
            }
            /**
             * <code>optional int32 start = 1;</code>
             */
            public Builder setStart(int value) {
                copyOnWrite();
                instance.setStart(value);
                return this;
            }
            /**
             * <code>optional int32 start = 1;</code>
             */
            public Builder clearStart() {
                copyOnWrite();
                instance.clearStart();
                return this;
            }

            /**
             * <code>optional int32 end = 2;</code>
             */
            public boolean hasEnd() {
                return instance.hasEnd();
            }
            /**
             * <code>optional int32 end = 2;</code>
             */
            public int getEnd() {
                return instance.getEnd();
            }
            /**
             * <code>optional int32 end = 2;</code>
             */
            public Builder setEnd(int value) {
                copyOnWrite();
                instance.setEnd(value);
                return this;
            }
            /**
             * <code>optional int32 end = 2;</code>
             */
            public Builder clearEnd() {
                copyOnWrite();
                instance.clearEnd();
                return this;
            }

            /**
             * <code>optional int32 flags = 3;</code>
             */
            public boolean hasFlags() {
                return instance.hasFlags();
            }
            /**
             * <code>optional int32 flags = 3;</code>
             */
            public int getFlags() {
                return instance.getFlags();
            }
            /**
             * <code>optional int32 flags = 3;</code>
             */
            public Builder setFlags(int value) {
                copyOnWrite();
                instance.setFlags(value);
                return this;
            }
            /**
             * <code>optional int32 flags = 3;</code>
             */
            public Builder clearFlags() {
                copyOnWrite();
                instance.clearFlags();
                return this;
            }

            /**
             * <code>optional .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType type = 4;</code>
             */
            public boolean hasType() {
                return instance.hasType();
            }
            /**
             * <code>optional .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType type = 4;</code>
             */
            public com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.SpanType getType() {
                return instance.getType();
            }
            /**
             * <code>optional .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType type = 4;</code>
             */
            public Builder setType(com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.SpanType value) {
                copyOnWrite();
                instance.setType(value);
                return this;
            }
            /**
             * <code>optional .com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto.SpanType type = 4;</code>
             */
            public Builder clearType() {
                copyOnWrite();
                instance.clearType();
                return this;
            }

            /**
             * <code>optional string url = 5;</code>
             */
            public boolean hasUrl() {
                return instance.hasUrl();
            }
            /**
             * <code>optional string url = 5;</code>
             */
            public java.lang.String getUrl() {
                return instance.getUrl();
            }
            /**
             * <code>optional string url = 5;</code>
             */
            public com.google.protobuf.ByteString
            getUrlBytes() {
                return instance.getUrlBytes();
            }
            /**
             * <code>optional string url = 5;</code>
             */
            public Builder setUrl(
                    java.lang.String value) {
                copyOnWrite();
                instance.setUrl(value);
                return this;
            }
            /**
             * <code>optional string url = 5;</code>
             */
            public Builder clearUrl() {
                copyOnWrite();
                instance.clearUrl();
                return this;
            }
            /**
             * <code>optional string url = 5;</code>
             */
            public Builder setUrlBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setUrlBytes(value);
                return this;
            }

            /**
             * <code>optional string span_class_name = 6;</code>
             */
            public boolean hasSpanClassName() {
                return instance.hasSpanClassName();
            }
            /**
             * <code>optional string span_class_name = 6;</code>
             */
            public java.lang.String getSpanClassName() {
                return instance.getSpanClassName();
            }
            /**
             * <code>optional string span_class_name = 6;</code>
             */
            public com.google.protobuf.ByteString
            getSpanClassNameBytes() {
                return instance.getSpanClassNameBytes();
            }
            /**
             * <code>optional string span_class_name = 6;</code>
             */
            public Builder setSpanClassName(
                    java.lang.String value) {
                copyOnWrite();
                instance.setSpanClassName(value);
                return this;
            }
            /**
             * <code>optional string span_class_name = 6;</code>
             */
            public Builder clearSpanClassName() {
                copyOnWrite();
                instance.clearSpanClassName();
                return this;
            }
            /**
             * <code>optional string span_class_name = 6;</code>
             */
            public Builder setSpanClassNameBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setSpanClassNameBytes(value);
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto)
        }
        protected final Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                Object arg0, Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto other = (com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto) arg1;
                    start_ = visitor.visitInt(
                            hasStart(), start_,
                            other.hasStart(), other.start_);
                    end_ = visitor.visitInt(
                            hasEnd(), end_,
                            other.hasEnd(), other.end_);
                    flags_ = visitor.visitInt(
                            hasFlags(), flags_,
                            other.hasFlags(), other.flags_);
                    type_ = visitor.visitInt(hasType(), type_,
                            other.hasType(), other.type_);
                    url_ = visitor.visitString(
                            hasUrl(), url_,
                            other.hasUrl(), other.url_);
                    spanClassName_ = visitor.visitString(
                            hasSpanClassName(), spanClassName_,
                            other.hasSpanClassName(), other.spanClassName_);
                    if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                            .INSTANCE) {
                        bitField0_ |= other.bitField0_;
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                            (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                            (com.google.protobuf.ExtensionRegistryLite) arg1;
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                default: {
                                    if (!parseUnknownField(tag, input)) {
                                        done = true;
                                    }
                                    break;
                                }
                                case 8: {
                                    bitField0_ |= 0x00000001;
                                    start_ = input.readInt32();
                                    break;
                                }
                                case 16: {
                                    bitField0_ |= 0x00000002;
                                    end_ = input.readInt32();
                                    break;
                                }
                                case 24: {
                                    bitField0_ |= 0x00000004;
                                    flags_ = input.readInt32();
                                    break;
                                }
                                case 32: {
                                    int rawValue = input.readEnum();
                                    com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.SpanType value = com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.SpanType.forNumber(rawValue);
                                    if (value == null) {
                                        super.mergeVarintField(4, rawValue);
                                    } else {
                                        bitField0_ |= 0x00000008;
                                        type_ = rawValue;
                                    }
                                    break;
                                }
                                case 42: {
                                    String s = input.readString();
                                    bitField0_ |= 0x00000010;
                                    url_ = s;
                                    break;
                                }
                                case 50: {
                                    String s = input.readString();
                                    bitField0_ |= 0x00000020;
                                    spanClassName_ = s;
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                                new com.google.protobuf.InvalidProtocolBufferException(
                                        e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {    synchronized (com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto.class) {
                        if (PARSER == null) {
                            PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                        }
                    }
                    }
                    return PARSER;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:com.google.android.apps.common.testing.accessibility.framework.uielement.proto.SpanProto)
        private static final com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new SpanProto();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static com.google.android.apps.common.testing.accessibility.framework.uielement.proto.AndroidFrameworkProtos.SpanProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<SpanProto> PARSER;

        public static com.google.protobuf.Parser<SpanProto> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
